apiVersion: v1
kind: ServiceAccount
metadata:
  name: trigger-job
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: trigger-job-role
rules:
- apiGroups: ["batch"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: trigger-job-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: trigger-job-role
subjects:
  - kind: ServiceAccount
    name: trigger-job
    namespace: default

